# Generated by Django 3.0.7 on 2020-08-21 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_order_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='color',
            field=models.CharField(default='DEFAULT VALUE', max_length=100),
        ),
    ]
